version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - 8080:8080
  redis:
    image: redis:latest
    ports: 
    - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"



